language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
after_success:
  - npm run build
deploy:
  provider: pages
  repo: benpryke/benpryke.github.io
  local_dir: build
  target_branch: master
  fqdn: www.benpryke.com
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
